const GET_RECIPES = 'GET_RECIPES';
const GET_TYPES_OF_DIET = 'GET_TYPES_OF_DIET';
const GET_RECIPES_BY_NAME = 'GET_RECIPES_BY_NAME';
const POST_RECIPES = 'POST_RECIPES';
const DELETE_RECIPE = 'DELETE_RECIPE';
const FILTER_BY_DIET = 'FILTER_BY_DIET';
const FILTER_CREATED = 'FILTER_CREATED';
const ORDER_BY_NAME = 'ORDER_BY_NAME';
const ORDER_BY_SCORE = 'ORDER_BY_SCORE';
const GET_DETAIL = 'GET_DETAIL';

module.exports = {
    GET_RECIPES,
    GET_TYPES_OF_DIET,
    GET_RECIPES_BY_NAME,
    POST_RECIPES,
    DELETE_RECIPE,
    FILTER_BY_DIET,
    FILTER_CREATED,
    ORDER_BY_NAME,
    ORDER_BY_SCORE,
    GET_DETAIL
}