const GET_RECIPES = 'GET_RECIPES';
const GET_TYPES_OF_DIET = 'GET_TYPES_OF_DIET';
const FILTER_BY_DIET = 'FILTER_BY_DIET';
const FILTER_CREATED = 'FILTER_CREATED';
const ORDER_BY_NAME = 'ORDER_BY_NAME';

module.exports = {
    GET_RECIPES,
    GET_TYPES_OF_DIET,
    FILTER_BY_DIET,
    FILTER_CREATED,
    ORDER_BY_NAME
}